name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bicep:
    name: Bicep Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bicep Build
        run: az bicep build --file main.bicep
        working-directory: bicep
